"""
Lab 05 — Verify Agent Memory Continuity
Day 1: Breakout Lab

TODO: Implement two invocations to verify short-term memory continuity.

After deploying your agent, invoke it twice with the same actorId and
sessionId. The second invocation should recall context from the first.

You will also inspect the trace in CloudWatch.
"""
import json
import os
import time
import uuid

import boto3

# --- Configuration ---
# TODO: Replace with your deployed agent runtime ARN
AGENT_RUNTIME_ARN = os.environ.get(
    "AGENT_RUNTIME_ARN",
    "arn:aws:bedrock-agentcore:us-east-1:123456789012:agent-runtime/LabAgent-Team01",  # ← REPLACE ME
)

# TODO: Set your actor ID (use your name or team prefix)
ACTOR_ID = os.environ.get("ACTOR_ID", "student-01")  # ← REPLACE ME

# Session ID — keep the same across both invocations for memory continuity
SESSION_ID = f"lab-session-{str(uuid.uuid4())[:8]}"

AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")

# Initialize the data plane client
agentcore = boto3.client("bedrock-agentcore", region_name=AWS_REGION)


def invoke_agent(actor_id: str, session_id: str, message: str, invocation_num: int):
    """Invoke the agent and print the response.

    The invoke_agent_runtime API sends a request to your Runtime endpoint.
    When using the same actorId and sessionId, the agent's Memory resource
    provides conversation continuity.
    """
    print(f"\n{'─' * 50}")
    print(f"  Invocation {invocation_num}")
    print(f"  Actor: {actor_id} | Session: {session_id}")
    print(f"  Message: {message}")

    # Build the invocation payload
    payload = json.dumps({"prompt": message}).encode("utf-8")

    # TODO: Uncomment to actually invoke your agent
    # response = agentcore.invoke_agent_runtime(
    #     agentRuntimeArn=AGENT_RUNTIME_ARN,
    #     runtimeSessionId=session_id,
    #     runtimeUserId=actor_id,
    #     contentType="application/json",
    #     payload=payload,
    # )
    #
    # # Process the streaming response
    # if "text/event-stream" in response.get("contentType", ""):
    #     event_stream = response["response"]
    #     for event in event_stream:
    #         if "chunk" in event:
    #             chunk = event["chunk"]["bytes"].decode("utf-8")
    #             print(f"  Response: {chunk}")
    # else:
    #     body = response["response"].read()
    #     print(f"  Response: {body.decode('utf-8')}")

    print(f"  [Simulated] Agent response received.")
    print(f"  Trace ID: {uuid.uuid4().hex[:16]}")


def main():
    print("=" * 60)
    print("  Agent Memory Continuity Verification")
    print("=" * 60)
    print(f"  Agent ARN: {AGENT_RUNTIME_ARN}")
    print(f"  Actor ID:  {ACTOR_ID}")
    print(f"  Session:   {SESSION_ID}")
    print()

    # --- Invocation 1: Set context ---
    # TODO: Implement the first invocation
    # The agent should remember this context for the next invocation
    invoke_agent(ACTOR_ID, SESSION_ID, "I need to book a flight to Seattle next Monday.", 1)

    # --- Invocation 2: Retrieve context ---
    # TODO: Implement the second invocation with the SAME actorId and sessionId
    # The agent should recall the flight destination from invocation 1
    invoke_agent(ACTOR_ID, SESSION_ID, "What is my destination?", 2)

    print(f"\n{'─' * 50}")
    print("\n  Verification complete!")
    print(f"\n  Next step: Navigate to CloudWatch → Generative AI Observability")
    print(f"  to inspect the traces generated by your invocations.")
    print(f"  Look for traces with session ID: {SESSION_ID}")


if __name__ == "__main__":
    main()
